# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/til/',
                'doc_host': 'https://masapasa.github.io',
                'git_url': 'https://github.com/masapasa/til/',
                'lib_path': 'til'},
  'syms': {}}
